<definitions name="HelloService" targetNamespace="http://www.examples.com/wsdl/HelloService.wsdl" 
  xmlns="http://schemas.xmlsoap.org/wsdl/" 
  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:tns="http://www.examples.com/wsdl/HelloService.wsdl" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <message name="getSubtractionRequest">
    <part name="x" type="xsd:float"/>
    <part name="y" type="xsd:float"/>
  </message>

  <message name="getSubtractionResponse">
    <part name="result" type="xsd:float"/>
  </message>

  <portType name="Hello_PortType">
    <operation name="subtractionCalculator">
      <input message="tns:getSubtractionRequest"/>
      <output message="tns:getSubtractionResponse"/>
    </operation>
  </portType>

  <binding name="Hello_Binding" type="tns:Hello_PortType">
    <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="subtractionCalculator">
      <soap:operation soapAction="subtractionCalculator"/>
      <input>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:examples:helloservice" use="encoded"/>
      </input>
      <output>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:examples:helloservice" use="encoded"/>
      </output>
    </operation>
  </binding>

  <service name="Subtraction_Service">
    <documentation>WSDL File for HelloService</documentation>
    <port binding="tns:Hello_Binding" name="Subtraction_Port">
      <soap:address location="http://localhost:3030/subtraction/" />
    </port>
  </service>
</definitions>